---
title: "Folate_ConBP_Females"
output: html_document
date: "2024-01-12"
---

#The heatmap (second) got into the folate_conBP_males folder -- fix this



Load RNA-sequencing data, Consensus between Brain and Placenta for males
```{r}
library(WGCNA)
library(readxl)

#only use samples that have 
#No PCB ; No Folic Acid (0 / No)
#No PCB ; Yes Folic Acid (0 / Yes)
#Yes PCB ; No Folic Acid (0.1 / No)
#Yes PCB ; Yes Folic Acid (0.1 / Yes)
#so take out samples that have 1PCB/6PCB (Groups C and D)


F_Brain <- read_excel("/Users/kchau/Documents/PEBBLES/Folate_ConMF_Brains/Folate_F_Brain_RNAseq.xlsx")
F_Brain1 <- F_Brain[!grepl("PLAC", colnames(F_Brain))]

F_Placenta <- read_excel("/Users/kchau/Documents/PEBBLES/Folate_ConMF_Placentas/F_Placenta_FA.xlsx")
F_Placenta1 <- F_Placenta[!grepl("BRAIN", colnames(F_Placenta))]

# Take a quick look at what is in the data sets (caution, longish output):
dim(F_Brain1)
names(F_Brain1)
dim(F_Placenta1)
names(F_Placenta1)
```


```{r}
intersectedgenes <- intersect(rownames(F_Brain1), rownames(F_Placenta1))
F_Brain1 <- F_Brain1[intersectedgenes, ]
F_Placenta1 <- F_Placenta1[intersectedgenes, ]
```

```{r}
# We work with two sets:
nSets = 2;
# For easier labeling of plots, create a vector holding descriptive names of the two sets.
setLabels = c("Female Brain", "Female Placenta")
shortLabels = c("Brain", "Placenta")
# Form multi-set expression data: columns starting from 9 contain actual expression data.
multiExpr = vector(mode = "list", length = nSets)
multiExpr[[1]] = list(data = as.data.frame(t(F_Brain1[-c(1:1)])));
names(multiExpr[[1]]$data) = F_Brain1$Gene;
rownames(multiExpr[[1]]$data) = names(F_Brain1)[-c(1:1)];
multiExpr[[2]] = list(data = as.data.frame(t(F_Placenta1[-c(1:1)])));
names(multiExpr[[2]]$data) = F_Placenta1$Gene;
rownames(multiExpr[[2]]$data) = names(F_Placenta1)[-c(1:1)];
```


```{r}
# Check that the data has the correct format for many functions operating on multiple sets:
exprSize = checkSets(multiExpr)
```

```{r}
# Check that all genes and samples have sufficiently low numbers of missing values.
gsg = goodSamplesGenesMS(multiExpr, verbose = 3);
gsg$allOK
```

```{r}
if (!gsg$allOK)
{
# Print information about the removed genes:
if (sum(!gsg$goodGenes) > 0)
printFlush(paste("Removing genes:", paste(names(multiExpr[[1]]$data)[!gsg$goodGenes],
collapse = ", ")))
for (set in 1:exprSize$nSets)
{
if (sum(!gsg$goodSamples[[set]]))
printFlush(paste("In set", setLabels[set], "removing samples",
paste(rownames(multiExpr[[set]]$data)[!gsg$goodSamples[[set]]], collapse = ", ")))
# Remove the offending genes and samples
multiExpr[[set]]$data = multiExpr[[set]]$data[gsg$goodSamples[[set]], gsg$goodGenes];
}
# Update exprSize
exprSize = checkSets(multiExpr)
}
```

```{r}
sampleTrees = list()
for (set in 1:nSets)
{
sampleTrees[[set]] = hclust(dist(multiExpr[[set]]$data), method = "average")
}
# dist_female <- dist(multiExpr[[1]]$data)
# dist_male <- dist(multiExpr[[2]]$data)
```

```{r}
pdf(file = "/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/FemaleBrainPlacentaSampleClustering.pdf", width = 12, height = 12);
par(mfrow=c(2,1))
par(mar = c(0, 4, 2, 0))
for (set in 1:nSets)
plot(sampleTrees[[set]], main = paste("Sample clustering on all genes in", setLabels[set]),
xlab="", sub="", cex = 0.7);
dev.off()
```

#remove 36_01 in female brain as outlier
```{r}
# Choose the "base" cut height for the female data set
baseHeight = 73
# Adjust the cut height for the male data set for the number of samples
cutHeights = c(73, 73*exprSize$nSamples[2]/exprSize$nSamples[1]);
#cutHeights = c(60, 100);
# Re-plot the dendrograms including the cut lines
pdf(file = "/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/SamplesClusteringCutoff_OutlierRemoval.pdf", width = 12, height = 12);
par(mfrow=c(2,1))
par(mar = c(0, 4, 2, 0))
for (set in 1:nSets)
{
plot(sampleTrees[[set]], main = paste("Sample clustering on all genes in", setLabels[set]),
xlab="", sub="", cex = 0.7);
abline(h=cutHeights[set], col = "red");
}
dev.off()
```

```{r}
#outlier removal
for (set in 1:nSets)
{
   #Find clusters cut by the line
   labels = cutreeStatic(sampleTrees[[set]], cutHeight = cutHeights[set], minSize = 10)
   #Keep the largest one (labeled by the number 1)
   keep = (labels==1)
   multiExpr[[set]]$data = multiExpr[[set]]$data[keep, ]
 }
 
 labels1 <- cutreeStatic(sampleTrees[[1]], cutHeight = 73)
 labels2 <- cutreeStatic(sampleTrees[[2]], cutHeight = 100, minSize = 10)
```

```{r}
collectGarbage();
# Check the size of the leftover data
exprSize = checkSets(multiExpr)
exprSize
```


```{r}
FolatetraitData = read_excel("/Users/kchau/Documents/PEBBLES/Folate_ConBP_Females/Folate_ConBP_Females_sampletraits.xlsx");

FolatetraitData <- FolatetraitData[, -c(2)]
```

```{r}
FAallTraits = FolatetraitData
# See how big the traits are and what are the trait and sample names
dim(FAallTraits)
names(FAallTraits)
FAallTraits$Name
```

```{r}
#two columns
FAallTraits <- FAallTraits[, -c(3, 5, 6, 8)]

```



```{r}
#FA
# Form a multi-set structure that will hold the sample traits.
FATraits = vector(mode="list", length = nSets);
for (set in 1:nSets)
{
FAsetSamples = rownames(multiExpr[[set]]$data);
FAtraitRows = match(FAsetSamples, FAallTraits$Name);
FATraits[[set]] = list(data = FAallTraits[FAtraitRows, -1]);
rownames(FATraits[[set]]$data) = as.data.frame(FAallTraits)[FAtraitRows, 1]
#rownames(PCBTraits[[set]]$data) = as.data.frame(PCBallTraits)[PCBtraitRows, 1];
}
collectGarbage();
# Define data set dimensions
FAnGenes = exprSize$nGenes;
FAnSamples = exprSize$nSamples;
```

```{r}
# Choose a set of soft-thresholding powers
powers = c(seq(4,10,by=1), seq(12,40, by=2));
# Initialize a list to hold the results of scale-free analysis
powerTables = vector(mode = "list", length = nSets);
# Call the network topology analysis function for each set in turn
for (set in 1:nSets)
powerTables[[set]] = list(data = pickSoftThreshold(multiExpr[[set]]$data, powerVector=powers,
verbose = 2)[[2]]);
collectGarbage();
# Plot the results:
colors = c("black", "red")
# Will plot these columns of the returned scale free analysis tables
plotCols = c(2,5,6,7)
colNames = c("Scale Free Topology Model Fit", "Mean connectivity", "Median connectivity",
"Max connectivity");
# Get the minima and maxima of the plotted points
ylim = matrix(NA, nrow = 2, ncol = 4);
for (set in 1:nSets)
{
for (col in 1:length(plotCols))
{
ylim[1, col] = min(ylim[1, col], powerTables[[set]]$data[, plotCols[col]], na.rm = TRUE);
ylim[2, col] = max(ylim[2, col], powerTables[[set]]$data[, plotCols[col]], na.rm = TRUE);
}
}
# Plot the quantities in the chosen columns vs. the soft thresholding power
sizeGrWindow(8, 6)
pdf(file = "/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/scaleFreeAnalysis.pdf", wi = 8, he = 6)
par(mfcol = c(2,2));
par(mar = c(4.2, 4.2 , 2.2, 0.5))
cex1 = 0.7;
for (col in 1:length(plotCols)) for (set in 1:nSets)
{
if (set==1)
{
plot(powerTables[[set]]$data[,1], -sign(powerTables[[set]]$data[,3])*powerTables[[set]]$data[,2],
xlab="Soft Threshold (power)",ylab=colNames[col],type="n", ylim = ylim[, col],
main = colNames[col]);
addGrid();
}
if (col==1)
{
text(powerTables[[set]]$data[,1], -sign(powerTables[[set]]$data[,3])*powerTables[[set]]$data[,2],
labels=powers,cex=cex1,col=colors[set]);
} else
text(powerTables[[set]]$data[,1], powerTables[[set]]$data[,plotCols[col]],
labels=powers,cex=cex1,col=colors[set]);
if (col==1)
{
legend("bottomright", legend = setLabels, col = colors, pch = 20) ;
} else
legend("topright", legend = setLabels, col = colors, pch = 20) ;
}
dev.off();
```

```{r}
bnet = blockwiseConsensusModules(
multiExpr, maxBlockSize = 2000, power = 24, minModuleSize = 100,
corType = "bicor", 
networkType = "signed",
TOMType = "signed",
deepSplit = 2,
pamRespectsDendro = FALSE,
mergeCutHeight = 0.25, numericLabels = TRUE,
minKMEtoStay = 0,
saveTOMs = TRUE, verbose = 5)
```



```{r}
names(bnet)
```

```{r}
FAconsMEs = bnet$multiMEs;
FAmoduleLabels = bnet$colors;
# Convert the numeric labels to color labels
FAmoduleColors = labels2colors(FAmoduleLabels)
FAconsTree = bnet$dendrograms[[1]]
```

```{r}
sizeGrWindow(12,6)

pdf(file = "/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/BlockwiseGeneDendrosAndColors.pdf", wi = 12, he = 6);
# Use the layout function for more involved screen sectioning
layout(matrix(c(1:4), 2, 2), heights = c(0.8, 0.2), widths = c(1,1))
#layout.show(4);
nBlocks = length(bnet$dendrograms)
# Plot the dendrogram and the module colors underneath for each block
for (block in 1:nBlocks)
plotDendroAndColors(bnet$dendrograms[[block]], FAmoduleColors[bnet$blockGenes[[block]]],
"Module colors",
main = paste("Consensus Brain/Placenta for Females Gene dendrogram and module colors in block", block),
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05,
setLayout = FALSE)
dev.off()
```


```{r}
#find number of modules
table(bnet$colors)
```

```{r}
# Set up variables to contain the module-trait correlations
FAmoduleTraitCor = list();
FAmoduleTraitPvalue = list();
# Calculate the correlations
for (set in 1:nSets)
{
FAmoduleTraitCor[[set]] = cor(FAconsMEs[[set]]$data, FATraits[[set]]$data, use = "p", method = "spearman");
FAmoduleTraitPvalue[[set]] = corPvalueFisher(FAmoduleTraitCor[[set]], exprSize$nSamples[set])
}
```

```{r}
# Convert numerical lables to colors for labeling of modules in the plot
FAMEColors = labels2colors(as.numeric(substring(names(FAconsMEs[[1]]$data), 3)));
FAMEColorNames = paste("ME", FAMEColors, sep="");
# Open a suitably sized window (the user should change the window size if necessary)
sizeGrWindow(11,9)
pdf(file = "/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/ConsensusModuleTraitRelationships-bicor-FABrain-twocolumn.pdf", wi = 4, he = 8);
# Plot the module-trait relationship table for set number 1
set = 1
textMatrix = paste(signif(FAmoduleTraitCor[[set]], 2), "\n(",
signif(FAmoduleTraitPvalue[[set]], 1), ")", sep = "");
dim(textMatrix) = dim(FAmoduleTraitCor[[set]])
par(mar = c(6, 8.8, 3, 2.2));
labeledHeatmap(Matrix = FAmoduleTraitCor[[set]],
xLabels = names(FATraits[[set]]$data),
yLabels = FAMEColorNames,
ySymbols = FAMEColorNames,
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
cex.text = 0.8,
zlim = c(-1,1),
main = paste("Module Eigengene Relationship with FA Dose in", setLabels[set]))
dev.off();
# Plot the module-trait relationship table for set number 2
set = 2
textMatrix = paste(signif(FAmoduleTraitCor[[set]], 2), "\n(",
signif(FAmoduleTraitPvalue[[set]], 1), ")", sep = "");
dim(textMatrix) = dim(FAmoduleTraitCor[[set]])
sizeGrWindow(11,9)
pdf(file = "/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/ConsensusModuleTraitRelationships-bicor-FAPlacenta-twocolumn.pdf", wi = 4, he = 8);
par(mar = c(6, 8.8, 3, 2.2));
labeledHeatmap(Matrix = FAmoduleTraitCor[[set]],
xLabels = names(FATraits[[set]]$data),
yLabels = FAMEColorNames,
ySymbols = FAMEColorNames,
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
cex.text = 0.8,
zlim = c(-1,1),
main = paste("Module Eigengene Relationship with FA Dose in", setLabels[set]))
dev.off()
```



```{r}
# Initialize matrices to hold the consensus correlation and p-value
FAconsensusCor = matrix(NA, nrow(FAmoduleTraitCor[[1]]), ncol(FAmoduleTraitCor[[1]]));
FAconsensusPvalue = matrix(NA, nrow(FAmoduleTraitCor[[1]]), ncol(FAmoduleTraitCor[[1]]));
# Find consensus negative correlations
FAnegative = FAmoduleTraitCor[[1]] < 0 & FAmoduleTraitCor[[2]] < 0;
FAconsensusCor[FAnegative] = pmax(FAmoduleTraitCor[[1]][FAnegative], FAmoduleTraitCor[[2]][FAnegative]);
FAconsensusPvalue[FAnegative] = pmax(FAmoduleTraitPvalue[[1]][FAnegative], FAmoduleTraitPvalue[[2]][FAnegative]);
# Find consensus positive correlations
FApositive = FAmoduleTraitCor[[1]] > 0 & FAmoduleTraitCor[[2]] > 0;
FAconsensusCor[FApositive] = pmin(FAmoduleTraitCor[[1]][FApositive], FAmoduleTraitCor[[2]][FApositive]);
FAconsensusPvalue[FApositive] = pmax(FAmoduleTraitPvalue[[1]][FApositive], FAmoduleTraitPvalue[[2]][FApositive])
```

```{r}
textMatrix = paste(signif(FAconsensusCor, 2), "\n(",
signif(FAconsensusPvalue, 1), ")", sep = "");
dim(textMatrix) = dim(FAmoduleTraitCor[[set]])
sizeGrWindow(10,7)
pdf(file = "/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/ModuleTraitRelationships-allcolumns-bicor-FAconsensus.pdf", wi = 6, he = 10);
par(mar = c(6, 8.8, 3, 2.2));
labeledHeatmap(Matrix = FAconsensusCor,
xLabels = names(FATraits[[set]]$data),
yLabels = FAMEColorNames,
ySymbols = FAMEColorNames,
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
cex.text = 0.7,
zlim = c(-1,1),
main = paste("Consensus brain/placenta female modules FA trait relationships across\n",
paste(setLabels, collapse = " and ")))
dev.off()
```

```{r}
textMatrix = paste(signif(FAconsensusCor, 2), "\n(",
signif(FAconsensusPvalue, 1), ")", sep = "");
dim(textMatrix) = dim(FAmoduleTraitCor[[set]])
sizeGrWindow(10,7)
pdf(file = "/Users/kchau/Desktop/ModuleTraitRelationships-twocolumn-bicor-FAconsensus.pdf", wi = 6, he = 15);
par(mar = c(6, 8.8, 3, 2.2));
labeledHeatmap(Matrix = FAconsensusCor,
xLabels = names(FATraits[[set]]$data),
yLabels = FAMEColorNames,
ySymbols = FAMEColorNames,
colorLabels = FALSE,
colors = blueWhiteRed(50),
textMatrix = textMatrix,
setStdMargins = FALSE,
cex.text = 0.7,
zlim = c(-1,1),
main = paste("Consensus brain/placenta female modules FA trait relationships across\n",
paste(setLabels, collapse = " and ")))
dev.off()
```




```{r}
# Create a variable weight that will hold just the Folic Acid trait of mice in both sets
FADose = vector(mode = "list", length = nSets);
for (set in 1:nSets)
{
FADose[[set]] = list(data = as.data.frame(FATraits[[set]]$data$Folic_Acid));
names(FADose[[set]]$data) = "Folic Acid"
}
# Recalculate consMEs to give them color names
consMEsC = multiSetMEs(multiExpr, universalColors = FAmoduleColors);
# We add the weight trait to the eigengenes and order them by consesus hierarchical clustering:
MET = consensusOrderMEs(addTraitToMEs(consMEsC, FADose))
```


```{r}
sizeGrWindow(8,10);
pdf(file = "/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/FAEigengeneNetworks.pdf", width= 15, height = 16);
par(cex = 1)
plotEigengeneNetworks(MET, setLabels, marDendro = c(0,2,2,1), marHeatmap = c(7,7,7,7), setMargins = TRUE,
zlimPreservation = c(0.5, 1), xLabelsAngle = 90)
dev.off()
```


```{r}
#find number of genes in each module
genes_per_module <- table(FAmoduleColors)
```

```{r}
library(data.table)
library(dplyr)
library(formattable)
library(tidyr)
```

```{r}
#orders from lowest number of genes to highest
genes_per_module <- arrange(data.frame(genes_per_module), Freq)

formattable(genes_per_module)
knitr::kable(genes_per_module, format = "html", col.names = c("Module", "Number of Genes"))

```


```{r}
# Create a variable weight that will hold just the Folic Acid trait of mice in both sets
FADose = vector(mode = "list", length = nSets);
for (set in 1:nSets)
{
FADose[[set]] = list(data = as.data.frame(FATraits[[set]]$data$Folic_Acid));
names(FADose[[set]]$data) = "Folic Acid"
}
# Recalculate consMEs to give them color names
consMEsC = multiSetMEs(multiExpr, universalColors = FAmoduleColors);
# We add the weight trait to the eigengenes and order them by consesus hierarchical clustering:
MET = consensusOrderMEs(addTraitToMEs(consMEsC, FADose))
```

```{r}
sizeGrWindow(8,10);
pdf(file = "/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/FAEigengeneNetworks.pdf", width= 14, height = 16);
par(cex = 1)
plotEigengeneNetworks(MET, setLabels, marDendro = c(0,2,2,1), marHeatmap = c(6,6,5,5), setMargins = TRUE,
zlimPreservation = c(0.5, 1), xLabelsAngle = 90)
dev.off()
```


```{r}
library("AnnotationDbi")
library("org.Mm.eg.db")
#columns(org.Mm.eg.db) # returns list of available keytypes
F_Brain1$entrez = mapIds(org.Mm.eg.db,
                    keys=F_Brain1$Gene, #Column containing Ensembl gene ids
                    column="ENTREZID",
                    keytype="ENSEMBL",
                    multiVals="first")
```

```{r}
#columns(org.Mm.eg.db) # returns list of available keytypes
F_Placenta1$entrez = mapIds(org.Mm.eg.db,
                    keys=F_Placenta1$Gene, #Column containing Ensembl gene ids
                    column="ENTREZID",
                    keytype="ENSEMBL",
                    multiVals="first")
```

```{r}
#GO Terms 
GOenrFemaleBrain = GOenrichmentAnalysis(FAmoduleColors, F_Brain1$entrez, organism = "mouse", evidence = "all", nBestP = 10)

#GO Terms 
GOenrFemalePlacenta = GOenrichmentAnalysis(FAmoduleColors, F_Placenta1$entrez, organism = "mouse", evidence = "all", nBestP = 10)
```

```{r}

tabFemaleBrain = GOenrFemaleBrain$bestPTerms[[4]]$enrichment
tabFemalePlacenta = GOenrFemalePlacenta$bestPTerms[[4]]$enrichment
```

#For Consensus GO terms
```{r}
consMEs.unord = multiSetMEs(multiExpr, universalColors = FAmoduleLabels, excludeGrey = TRUE)
GS = list();
kME = list();
for (set in 1:nSets)
{
GS[[set]] = corAndPvalue(multiExpr[[set]]$data, FATraits[[set]]$data);
kME[[set]] = corAndPvalue(multiExpr[[set]]$data, consMEs.unord[[set]]$data);
}
```


```{r}
GS.metaZ = (GS[[1]]$Z + GS[[2]]$Z)/sqrt(2);
kME.metaZ = (kME[[1]]$Z + kME[[2]]$Z)/sqrt(2);
GS.metaP = 2*pnorm(abs(GS.metaZ), lower.tail = FALSE);
kME.metaP = 2*pnorm(abs(kME.metaZ), lower.tail = FALSE)
```

```{r}
GSmat = rbind(GS[[1]]$cor, GS[[2]]$cor, GS[[1]]$p, GS[[2]]$p, GS.metaZ, GS.metaP);
nTraits = checkSets(FATraits)$nGenes
traitNames = colnames(FATraits[[1]]$data)
dim(GSmat) = c(FAnGenes, 6*nTraits)
#rownames(GSmat) = probes;
rownames(GSmat) = F_Brain1$Gene;
colnames(GSmat) = spaste(
c("GS.set1.", "GS.set2.", "p.GS.set1.", "p.GS.set2.", "Z.GS.meta.", "p.GS.meta"),
rep(traitNames, rep(6, nTraits)))
# Same code for kME:
kMEmat = rbind(kME[[1]]$cor, kME[[2]]$cor, kME[[1]]$p, kME[[2]]$p, kME.metaZ, kME.metaP);
MEnames = colnames(consMEs.unord[[1]]$data);
nMEs = checkSets(consMEs.unord)$nGenes
dim(kMEmat) = c(FAnGenes, 6*nMEs)
#rownames(kMEmat) = probes;
rownames(kMEmat) = F_Brain1$Gene;
colnames(kMEmat) = spaste(
c("kME.set1.", "kME.set2.", "p.kME.set1.", "p.kME.set2.", "Z.kME.meta.", "p.kME.meta"),
rep(MEnames, rep(6, nMEs)))
```

```{r}
info = data.frame(Probe = F_Brain1$Gene, EntrezID = F_Brain1$entrez,
ModuleLabel = FAmoduleLabels,
ModuleColor = labels2colors(FAmoduleLabels), GSmat, kMEmat);
write.csv(info, file = "/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/brain_consensusAnalysis-CombinedNetworkResults.csv",
row.names = FALSE, quote = FALSE)
```

```{r}
info <- info[, 1:4]
info$GeneSymbol <- 'NA'

#Convert entrezID to gene symbols using biomart
library(biomaRt)
library(dplyr)
#library(xlsx)


mart <- useDataset("mmusculus_gene_ensembl", useMart("ensembl"))
#got the probe and gene symbol that matches
geneSymbols <- getBM(filters = "ensembl_gene_id", attributes= c("ensembl_gene_id", "external_gene_name"), values=info$Probe, mart= mart)

#join the dataframe with moduleinfo by Probe column
joinGeneSymbol <- left_join(info, geneSymbols, by = c("Probe" = "ensembl_gene_id"))
```

```{r}
kMEcols <- grep("^Z.kME.meta", colnames(info), value = TRUE)

hubTable <- do.call(rbind, lapply(kMEcols, function(colname) {

  ME <- sub("^Z.kME.meta.", "", colname)

  # extract numeric ME index (ME1 -> 1)
  MEidx <- as.numeric(sub("^ME", "", ME))

  # genes assigned to this module by clustering
  genesInModule <- info$ModuleLabel == MEidx

  if (!any(genesInModule)) return(NULL)

  zvals <- as.numeric(info[[colname]])

  info[genesInModule, ][
    which.max(abs(zvals[genesInModule])),
  ]
}))

```

```{r}
joinGeneSymbol <- joinGeneSymbol[ , -c(5:107)]
```







```{r}
library(enrichR)
#split function
modulecolors_split <- split(joinGeneSymbol, joinGeneSymbol$ModuleColor)


# Assuming you have a list of module colors and their corresponding data frames
#module_colors <- c('red', 'blue', 'green', ...)  # Add other module colors as needed
#module_data_frames <- list(red = redmodule, blue = bluemodule, green = greenmodule, ...)  # Replace with actual data frames for other modules

# Create a function to perform enrichment analysis and save the results
perform_enrichment <- function(module_color, module_data) {
  enriched_data <- enrichR::enrichr(
    module_data$external_gene_name,
    c('GO_Biological_Process_2023', 'GO_Cellular_Component_2023', 'GO_Molecular_Function_2023', 'KEGG_2021_Human')
  )
  file_path <- sprintf("/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/GO_terms/%s_excel.xlsx", module_color)
  openxlsx::write.xlsx(enriched_data, file_path)
}

# Loop through each module color and perform enrichment analysis
for (color in names(modulecolors_split)) {
  module_data <- modulecolors_split[[color]]
  perform_enrichment(color, module_data)
}
```
```{r}
library(enrichR)
#split function
modulecolors_split <- split(joinGeneSymbol, joinGeneSymbol$ModuleColor)


# Assuming you have a list of module colors and their corresponding data frames
#module_colors <- c('red', 'blue', 'green', ...)  # Add other module colors as needed
#module_data_frames <- list(red = redmodule, blue = bluemodule, green = greenmodule, ...)  # Replace with actual data frames for other modules

# Create a function to perform enrichment analysis and save the results
perform_enrichment <- function(module_color, module_data) {
  enriched_data <- enrichR::enrichr(
    module_data$external_gene_name,
    c('CellMarker_2024')
  )
  file_path <- sprintf("/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/CellMarkerEnrichments/%s_excel.xlsx", module_color)
  openxlsx::write.xlsx(enriched_data, file_path)
}

# Loop through each module color and perform enrichment analysis
for (color in names(modulecolors_split)) {
  module_data <- modulecolors_split[[color]]
  perform_enrichment(color, module_data)
}
```











```{r}
save(list = ls(.GlobalEnv), file = "/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/Renv.Rdata")
```





```{r}
MEtrait = read_excel("/Users/kchau/Documents/PEBBLES/Folate_ConBP_Females/Folate_ConBP_Females_sampletraits.xlsx");

#MEtrait <- MEtrait[, -c(2, 3)]

MEtrait$PCB_dose[MEtrait$PCB_dose == '0'] <- 'NO_PCB'
MEtrait$PCB_dose[MEtrait$PCB_dose == '1'] <- 'YES_PCB'
MEtrait$Folic_Acid[MEtrait$Folic_Acid == '0'] <- 'NO_FA'
MEtrait$Folic_Acid[MEtrait$Folic_Acid == '1'] <- 'YES_FA'

brainMEtrait <- MEtrait %>% filter(MEtrait$Tissue == "Brain")

brainME_magenta_traits <- cbind(brainMEtrait, MET[[1]]$data$MEmagenta)

#femaleME_purple_traits$ <- as.factor(femaleME_purple_traits$PCB_dose)


brainME_magenta_traits$FA_PCB <- paste(brainME_magenta_traits$Folic_Acid, brainME_magenta_traits$PCB_dose, sep = "/")



brainME_magenta_traits$FA_PCB <- as.factor(brainME_magenta_traits$FA_PCB)
levels(brainME_magenta_traits$FA_PCB)

brainME_magenta_traits$FA_PCB <- factor(brainME_magenta_traits$FA_PCB, levels=c('NO_FA/NO_PCB', 'YES_FA/NO_PCB', 'NO_FA/YES_PCB', 'YES_FA/YES_PCB'))


ggplotmagenta_brain <- ggplot(data = brainME_magenta_traits, aes(x = FA_PCB, y = MET[[1]]$data$MEmagenta, color = FA_PCB)) + geom_boxplot() + geom_point() + ggtitle("Female Brain: Eigengene Values in Magenta Module") + xlab("Folic Acid / PCB") + ylab("Module Eigengene Values")

ggplotmagenta_brain + geom_point(size=3) + ylim(-0.5, 0.5) + theme_classic() + theme(text = element_text(size=12)) + theme(axis.text=element_text(size=14, face = "bold"), axis.title=element_text(size=16,face="bold")) + theme(plot.title = element_text(face="bold")) + theme(plot.title = element_text(size=18)) + theme(plot.title = element_text(hjust = 0.5))

```

```{r}
placentaMEtrait <- MEtrait %>% filter(MEtrait$Tissue == "Placenta")

#placentaMEtrait <- placentaMEtrait[-c(26,27),] #remove outlier 35_05 and 35_06

placentaME_magenta_traits <- cbind(placentaMEtrait, MET[[2]]$data$MEmagenta)

#femaleME_purple_traits$ <- as.factor(femaleME_purple_traits$PCB_dose)


placentaME_magenta_traits$FA_PCB <- paste(placentaME_magenta_traits$Folic_Acid, placentaME_magenta_traits$PCB_dose, sep = "/")



placentaME_magenta_traits$FA_PCB <- as.factor(placentaME_magenta_traits$FA_PCB)
levels(placentaME_magenta_traits$FA_PCB)

placentaME_magenta_traits$FA_PCB <- factor(placentaME_magenta_traits$FA_PCB, levels=c('NO_FA/NO_PCB', 'YES_FA/NO_PCB', 'NO_FA/YES_PCB', 'YES_FA/YES_PCB'))


ggplotmagenta_placenta <- ggplot(data = placentaME_magenta_traits, aes(x = FA_PCB, y = MET[[2]]$data$MEmagenta, color = FA_PCB)) + geom_boxplot() + geom_point() + ggtitle("Female Placenta: Eigengene Values in Magenta Module") + xlab("Folic Acid / PCB") + ylab("Module Eigengene Values")

ggplotmagenta_placenta + geom_point(size=3) + ylim(-0.5, 0.5) + theme_classic() + theme(text = element_text(size=12)) + theme(axis.text=element_text(size=14, face = "bold"), axis.title=element_text(size=16,face="bold")) + theme(plot.title = element_text(face="bold")) + theme(plot.title = element_text(size=18)) + theme(plot.title = element_text(hjust = 0.5))

```

```{r}
brainME_magenta_traits$Folic_Acid[brainME_magenta_traits$Folic_Acid == 'NO_FA'] <- 'No Folic Acid'
brainME_magenta_traits$Folic_Acid[brainME_magenta_traits$Folic_Acid == 'YES_FA'] <- 'Yes Folic Acid'

brainME_magenta_traits$PCB_dose[brainME_magenta_traits$PCB_dose == 'NO_PCB'] <- '0'
brainME_magenta_traits$PCB_dose[brainME_magenta_traits$PCB_dose == 'YES_PCB'] <- '0.1'
```

```{r}
#new plot
new_ggplotmagenta_brain <- ggplot(data = brainME_magenta_traits) +
  aes(x = PCB_dose, y = MET[[1]]$data$MEmagenta, color = Folic_Acid) + 
  geom_boxplot(lwd = 1, position = position_dodge(width = 0.9)) + 
  geom_point(size = 3, position = position_dodge(width = 0.9)) + 
  geom_smooth(method = lm, se = FALSE, mapping = aes(group = Folic_Acid), position = position_dodge(width = 1)) +
  ggtitle("Female Brain: Eigengene Values in Magenta Module") +
  xlab("PCB (mg/kg/day)") + 
  ylab("Module Eigengene Values") +
  theme(axis.text=element_text(size=12, face = "bold"), axis.title=element_text(size=14,face="bold")) +
  theme(plot.title = element_text(face="bold")) +
  theme(text = element_text(size=12, face="bold")) +
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}
new_ggplotmagenta_brain + labs(color='Folic Acid') 
```

#placenta magenta module

```{r}
placentaME_magenta_traits$Folic_Acid[placentaME_magenta_traits$Folic_Acid == 'NO_FA'] <- 'No Folic Acid'
placentaME_magenta_traits$Folic_Acid[placentaME_magenta_traits$Folic_Acid == 'YES_FA'] <- 'Yes Folic Acid'

placentaME_magenta_traits$PCB_dose[placentaME_magenta_traits$PCB_dose == 'NO_PCB'] <- '0'
placentaME_magenta_traits$PCB_dose[placentaME_magenta_traits$PCB_dose == 'YES_PCB'] <- '0.1'
```

```{r}
#new plot
new_ggplotmagenta_placenta <- ggplot(data = placentaME_magenta_traits) +
  aes(x = PCB_dose, y = MET[[2]]$data$MEmagenta, color = Folic_Acid) + 
  geom_boxplot(lwd = 1, position = position_dodge(width = 0.9)) + 
  geom_point(size = 3, position = position_dodge(width = 0.9)) + 
  geom_smooth(method = lm, se = FALSE, mapping = aes(group = Folic_Acid), position = position_dodge(width = 1)) +
  ggtitle("Female Placenta: Eigengene Values in Magenta Module") +
  xlab("PCB (mg/kg/day)") + 
  ylab("Module Eigengene Values") +
  theme(axis.text=element_text(size=12, face = "bold"), axis.title=element_text(size=14,face="bold")) +
  theme(plot.title = element_text(face="bold")) +
  theme(text = element_text(size=12, face="bold")) +
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}
new_ggplotmagenta_placenta + labs(color='Folic Acid') 
```


```{r}
ConTissue_Females_FA_genes_in_module <- joinGeneSymbol[ , c(4, 6)]
library(dplyr)
library(tidyr)
library(data.table)

ConTissue_Females_FA_genes_in_module <- distinct(ConTissue_Females_FA_genes_in_module) %>% 
  mutate(rn = rowid(ModuleColor)) %>%
  pivot_wider(names_from = rn, values_from = external_gene_name, 
    names_sep = "", values_fill = "")
    
library(tidyverse)

ConTissue_Females_FA_genes_in_module <- ConTissue_Females_FA_genes_in_module %>% 
  column_to_rownames(var = "ModuleColor")   
  
ConTissue_Females_FA_genes_in_module <- t(ConTissue_Females_FA_genes_in_module)
    
ConTissue_Females_FA_genes_in_module <- as.data.frame(ConTissue_Females_FA_genes_in_module)



writexl::write_xlsx(ConTissue_Females_FA_genes_in_module, "/Users/kchau/Documents/WGCNA/Folate_ConBP_Females/ConTissue_Females_FA_genes_in_module.xlsx")

```

